// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: pwbox.proto at 9:1
package com.common.bean;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class BaseRes extends Message<BaseRes, BaseRes.Builder> {
  public static final ProtoAdapter<BaseRes> ADAPTER = new ProtoAdapter_BaseRes();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_RETCODE = 0;

  public static final String DEFAULT_DESCRIPTION = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer retCode;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String description;

  public BaseRes(Integer retCode, String description) {
    this(retCode, description, ByteString.EMPTY);
  }

  public BaseRes(Integer retCode, String description, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.retCode = retCode;
    this.description = description;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.retCode = retCode;
    builder.description = description;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof BaseRes)) return false;
    BaseRes o = (BaseRes) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(retCode, o.retCode)
        && Internal.equals(description, o.description);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (retCode != null ? retCode.hashCode() : 0);
      result = result * 37 + (description != null ? description.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (retCode != null) builder.append(", retCode=").append(retCode);
    if (description != null) builder.append(", description=").append(description);
    return builder.replace(0, 2, "BaseRes{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<BaseRes, Builder> {
    public Integer retCode;

    public String description;

    public Builder() {
    }

    public Builder retCode(Integer retCode) {
      this.retCode = retCode;
      return this;
    }

    public Builder description(String description) {
      this.description = description;
      return this;
    }

    @Override
    public BaseRes build() {
      return new BaseRes(retCode, description, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_BaseRes extends ProtoAdapter<BaseRes> {
    ProtoAdapter_BaseRes() {
      super(FieldEncoding.LENGTH_DELIMITED, BaseRes.class);
    }

    @Override
    public int encodedSize(BaseRes value) {
      return (value.retCode != null ? ProtoAdapter.INT32.encodedSizeWithTag(1, value.retCode) : 0)
          + (value.description != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.description) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, BaseRes value) throws IOException {
      if (value.retCode != null) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.retCode);
      if (value.description != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.description);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public BaseRes decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.retCode(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.description(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public BaseRes redact(BaseRes value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
