// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: myssl.proto at 5:1
package com.common.bean;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * option java_package = "com.common.bean";
 */
public final class DataWithLen extends Message<DataWithLen, DataWithLen.Builder> {
  public static final ProtoAdapter<DataWithLen> ADAPTER = new ProtoAdapter_DataWithLen();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_LEN = 0;

  public static final ByteString DEFAULT_DATA = ByteString.EMPTY;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer len;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES"
  )
  public final ByteString data;

  public DataWithLen(Integer len, ByteString data) {
    this(len, data, ByteString.EMPTY);
  }

  public DataWithLen(Integer len, ByteString data, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.len = len;
    this.data = data;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.len = len;
    builder.data = data;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof DataWithLen)) return false;
    DataWithLen o = (DataWithLen) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(len, o.len)
        && Internal.equals(data, o.data);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (len != null ? len.hashCode() : 0);
      result = result * 37 + (data != null ? data.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (len != null) builder.append(", len=").append(len);
    if (data != null) builder.append(", data=").append(data);
    return builder.replace(0, 2, "DataWithLen{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<DataWithLen, Builder> {
    public Integer len;

    public ByteString data;

    public Builder() {
    }

    public Builder len(Integer len) {
      this.len = len;
      return this;
    }

    public Builder data(ByteString data) {
      this.data = data;
      return this;
    }

    @Override
    public DataWithLen build() {
      return new DataWithLen(len, data, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_DataWithLen extends ProtoAdapter<DataWithLen> {
    ProtoAdapter_DataWithLen() {
      super(FieldEncoding.LENGTH_DELIMITED, DataWithLen.class);
    }

    @Override
    public int encodedSize(DataWithLen value) {
      return (value.len != null ? ProtoAdapter.INT32.encodedSizeWithTag(1, value.len) : 0)
          + (value.data != null ? ProtoAdapter.BYTES.encodedSizeWithTag(2, value.data) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, DataWithLen value) throws IOException {
      if (value.len != null) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.len);
      if (value.data != null) ProtoAdapter.BYTES.encodeWithTag(writer, 2, value.data);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public DataWithLen decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.len(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.data(ProtoAdapter.BYTES.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public DataWithLen redact(DataWithLen value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
