// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: myssl.proto at 30:1
package com.common.bean;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class GetCommunicateKeyResponse extends Message<GetCommunicateKeyResponse, GetCommunicateKeyResponse.Builder> {
  public static final ProtoAdapter<GetCommunicateKeyResponse> ADAPTER = new ProtoAdapter_GetCommunicateKeyResponse();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_RET_CODE = 0;

  public static final String DEFAULT_ERROR_MESSAGE = "";

  public static final ByteString DEFAULT_RANDOM1 = ByteString.EMPTY;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer ret_code;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String error_message;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES"
  )
  public final ByteString random1;

  public GetCommunicateKeyResponse(Integer ret_code, String error_message, ByteString random1) {
    this(ret_code, error_message, random1, ByteString.EMPTY);
  }

  public GetCommunicateKeyResponse(Integer ret_code, String error_message, ByteString random1, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.ret_code = ret_code;
    this.error_message = error_message;
    this.random1 = random1;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.ret_code = ret_code;
    builder.error_message = error_message;
    builder.random1 = random1;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetCommunicateKeyResponse)) return false;
    GetCommunicateKeyResponse o = (GetCommunicateKeyResponse) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(ret_code, o.ret_code)
        && Internal.equals(error_message, o.error_message)
        && Internal.equals(random1, o.random1);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (ret_code != null ? ret_code.hashCode() : 0);
      result = result * 37 + (error_message != null ? error_message.hashCode() : 0);
      result = result * 37 + (random1 != null ? random1.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (ret_code != null) builder.append(", ret_code=").append(ret_code);
    if (error_message != null) builder.append(", error_message=").append(error_message);
    if (random1 != null) builder.append(", random1=").append(random1);
    return builder.replace(0, 2, "GetCommunicateKeyResponse{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GetCommunicateKeyResponse, Builder> {
    public Integer ret_code;

    public String error_message;

    public ByteString random1;

    public Builder() {
    }

    public Builder ret_code(Integer ret_code) {
      this.ret_code = ret_code;
      return this;
    }

    public Builder error_message(String error_message) {
      this.error_message = error_message;
      return this;
    }

    public Builder random1(ByteString random1) {
      this.random1 = random1;
      return this;
    }

    @Override
    public GetCommunicateKeyResponse build() {
      return new GetCommunicateKeyResponse(ret_code, error_message, random1, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetCommunicateKeyResponse extends ProtoAdapter<GetCommunicateKeyResponse> {
    ProtoAdapter_GetCommunicateKeyResponse() {
      super(FieldEncoding.LENGTH_DELIMITED, GetCommunicateKeyResponse.class);
    }

    @Override
    public int encodedSize(GetCommunicateKeyResponse value) {
      return (value.ret_code != null ? ProtoAdapter.INT32.encodedSizeWithTag(1, value.ret_code) : 0)
          + (value.error_message != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.error_message) : 0)
          + (value.random1 != null ? ProtoAdapter.BYTES.encodedSizeWithTag(3, value.random1) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, GetCommunicateKeyResponse value) throws IOException {
      if (value.ret_code != null) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.ret_code);
      if (value.error_message != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.error_message);
      if (value.random1 != null) ProtoAdapter.BYTES.encodeWithTag(writer, 3, value.random1);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetCommunicateKeyResponse decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.ret_code(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.error_message(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.random1(ProtoAdapter.BYTES.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public GetCommunicateKeyResponse redact(GetCommunicateKeyResponse value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
