// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: myssl.proto at 25:1
package com.common.bean;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class GetCommunicateKeyRequest extends Message<GetCommunicateKeyRequest, GetCommunicateKeyRequest.Builder> {
  public static final ProtoAdapter<GetCommunicateKeyRequest> ADAPTER = new ProtoAdapter_GetCommunicateKeyRequest();

  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_RANDOM1 = ByteString.EMPTY;

  public static final ByteString DEFAULT_RANDOM2 = ByteString.EMPTY;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES"
  )
  public final ByteString random1;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES"
  )
  public final ByteString random2;

  public GetCommunicateKeyRequest(ByteString random1, ByteString random2) {
    this(random1, random2, ByteString.EMPTY);
  }

  public GetCommunicateKeyRequest(ByteString random1, ByteString random2, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.random1 = random1;
    this.random2 = random2;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.random1 = random1;
    builder.random2 = random2;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetCommunicateKeyRequest)) return false;
    GetCommunicateKeyRequest o = (GetCommunicateKeyRequest) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(random1, o.random1)
        && Internal.equals(random2, o.random2);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (random1 != null ? random1.hashCode() : 0);
      result = result * 37 + (random2 != null ? random2.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (random1 != null) builder.append(", random1=").append(random1);
    if (random2 != null) builder.append(", random2=").append(random2);
    return builder.replace(0, 2, "GetCommunicateKeyRequest{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GetCommunicateKeyRequest, Builder> {
    public ByteString random1;

    public ByteString random2;

    public Builder() {
    }

    public Builder random1(ByteString random1) {
      this.random1 = random1;
      return this;
    }

    public Builder random2(ByteString random2) {
      this.random2 = random2;
      return this;
    }

    @Override
    public GetCommunicateKeyRequest build() {
      return new GetCommunicateKeyRequest(random1, random2, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetCommunicateKeyRequest extends ProtoAdapter<GetCommunicateKeyRequest> {
    ProtoAdapter_GetCommunicateKeyRequest() {
      super(FieldEncoding.LENGTH_DELIMITED, GetCommunicateKeyRequest.class);
    }

    @Override
    public int encodedSize(GetCommunicateKeyRequest value) {
      return (value.random1 != null ? ProtoAdapter.BYTES.encodedSizeWithTag(1, value.random1) : 0)
          + (value.random2 != null ? ProtoAdapter.BYTES.encodedSizeWithTag(2, value.random2) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, GetCommunicateKeyRequest value) throws IOException {
      if (value.random1 != null) ProtoAdapter.BYTES.encodeWithTag(writer, 1, value.random1);
      if (value.random2 != null) ProtoAdapter.BYTES.encodeWithTag(writer, 2, value.random2);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetCommunicateKeyRequest decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.random1(ProtoAdapter.BYTES.decode(reader)); break;
          case 2: builder.random2(ProtoAdapter.BYTES.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public GetCommunicateKeyRequest redact(GetCommunicateKeyRequest value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
