// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: myssl.proto at 15:1
package com.common.bean;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class GetPublicKeyResponse extends Message<GetPublicKeyResponse, GetPublicKeyResponse.Builder> {
  public static final ProtoAdapter<GetPublicKeyResponse> ADAPTER = new ProtoAdapter_GetPublicKeyResponse();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_RET_CODE = 0;

  public static final String DEFAULT_ERROR_MESSAGE = "";

  public static final Integer DEFAULT_VER = 0;

  public static final ByteString DEFAULT_PUBLIC_KEY = ByteString.EMPTY;

  public static final ByteString DEFAULT_PUB_EXPONENT = ByteString.EMPTY;

  public static final Integer DEFAULT_COMKEY_LEN = 0;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer ret_code;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String error_message;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer ver;

  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES"
  )
  public final ByteString public_key;

  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES"
  )
  public final ByteString pub_exponent;

  @WireField(
      tag = 6,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer comkey_len;

  public GetPublicKeyResponse(Integer ret_code, String error_message, Integer ver, ByteString public_key, ByteString pub_exponent, Integer comkey_len) {
    this(ret_code, error_message, ver, public_key, pub_exponent, comkey_len, ByteString.EMPTY);
  }

  public GetPublicKeyResponse(Integer ret_code, String error_message, Integer ver, ByteString public_key, ByteString pub_exponent, Integer comkey_len, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.ret_code = ret_code;
    this.error_message = error_message;
    this.ver = ver;
    this.public_key = public_key;
    this.pub_exponent = pub_exponent;
    this.comkey_len = comkey_len;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.ret_code = ret_code;
    builder.error_message = error_message;
    builder.ver = ver;
    builder.public_key = public_key;
    builder.pub_exponent = pub_exponent;
    builder.comkey_len = comkey_len;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetPublicKeyResponse)) return false;
    GetPublicKeyResponse o = (GetPublicKeyResponse) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(ret_code, o.ret_code)
        && Internal.equals(error_message, o.error_message)
        && Internal.equals(ver, o.ver)
        && Internal.equals(public_key, o.public_key)
        && Internal.equals(pub_exponent, o.pub_exponent)
        && Internal.equals(comkey_len, o.comkey_len);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (ret_code != null ? ret_code.hashCode() : 0);
      result = result * 37 + (error_message != null ? error_message.hashCode() : 0);
      result = result * 37 + (ver != null ? ver.hashCode() : 0);
      result = result * 37 + (public_key != null ? public_key.hashCode() : 0);
      result = result * 37 + (pub_exponent != null ? pub_exponent.hashCode() : 0);
      result = result * 37 + (comkey_len != null ? comkey_len.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (ret_code != null) builder.append(", ret_code=").append(ret_code);
    if (error_message != null) builder.append(", error_message=").append(error_message);
    if (ver != null) builder.append(", ver=").append(ver);
    if (public_key != null) builder.append(", public_key=").append(public_key);
    if (pub_exponent != null) builder.append(", pub_exponent=").append(pub_exponent);
    if (comkey_len != null) builder.append(", comkey_len=").append(comkey_len);
    return builder.replace(0, 2, "GetPublicKeyResponse{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GetPublicKeyResponse, Builder> {
    public Integer ret_code;

    public String error_message;

    public Integer ver;

    public ByteString public_key;

    public ByteString pub_exponent;

    public Integer comkey_len;

    public Builder() {
    }

    public Builder ret_code(Integer ret_code) {
      this.ret_code = ret_code;
      return this;
    }

    public Builder error_message(String error_message) {
      this.error_message = error_message;
      return this;
    }

    public Builder ver(Integer ver) {
      this.ver = ver;
      return this;
    }

    public Builder public_key(ByteString public_key) {
      this.public_key = public_key;
      return this;
    }

    public Builder pub_exponent(ByteString pub_exponent) {
      this.pub_exponent = pub_exponent;
      return this;
    }

    public Builder comkey_len(Integer comkey_len) {
      this.comkey_len = comkey_len;
      return this;
    }

    @Override
    public GetPublicKeyResponse build() {
      return new GetPublicKeyResponse(ret_code, error_message, ver, public_key, pub_exponent, comkey_len, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetPublicKeyResponse extends ProtoAdapter<GetPublicKeyResponse> {
    ProtoAdapter_GetPublicKeyResponse() {
      super(FieldEncoding.LENGTH_DELIMITED, GetPublicKeyResponse.class);
    }

    @Override
    public int encodedSize(GetPublicKeyResponse value) {
      return (value.ret_code != null ? ProtoAdapter.INT32.encodedSizeWithTag(1, value.ret_code) : 0)
          + (value.error_message != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.error_message) : 0)
          + (value.ver != null ? ProtoAdapter.INT32.encodedSizeWithTag(3, value.ver) : 0)
          + (value.public_key != null ? ProtoAdapter.BYTES.encodedSizeWithTag(4, value.public_key) : 0)
          + (value.pub_exponent != null ? ProtoAdapter.BYTES.encodedSizeWithTag(5, value.pub_exponent) : 0)
          + (value.comkey_len != null ? ProtoAdapter.INT32.encodedSizeWithTag(6, value.comkey_len) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, GetPublicKeyResponse value) throws IOException {
      if (value.ret_code != null) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.ret_code);
      if (value.error_message != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.error_message);
      if (value.ver != null) ProtoAdapter.INT32.encodeWithTag(writer, 3, value.ver);
      if (value.public_key != null) ProtoAdapter.BYTES.encodeWithTag(writer, 4, value.public_key);
      if (value.pub_exponent != null) ProtoAdapter.BYTES.encodeWithTag(writer, 5, value.pub_exponent);
      if (value.comkey_len != null) ProtoAdapter.INT32.encodeWithTag(writer, 6, value.comkey_len);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetPublicKeyResponse decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.ret_code(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.error_message(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.ver(ProtoAdapter.INT32.decode(reader)); break;
          case 4: builder.public_key(ProtoAdapter.BYTES.decode(reader)); break;
          case 5: builder.pub_exponent(ProtoAdapter.BYTES.decode(reader)); break;
          case 6: builder.comkey_len(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public GetPublicKeyResponse redact(GetPublicKeyResponse value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
