package com.pw.box.core.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.pw.box.core.db.bean.DbBean;
import com.pw.box.core.db.bean.SearchHistory;
import com.pw.box.core.db.bean.RecentItem;
import com.pw.box.core.db.bean.Kvs;
import com.pw.box.core.db.bean.OfflineItem;

import com.pw.box.core.db.DbBeanDao;
import com.pw.box.core.db.SearchHistoryDao;
import com.pw.box.core.db.RecentItemDao;
import com.pw.box.core.db.KvsDao;
import com.pw.box.core.db.OfflineItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dbBeanDaoConfig;
    private final DaoConfig searchHistoryDaoConfig;
    private final DaoConfig recentItemDaoConfig;
    private final DaoConfig kvsDaoConfig;
    private final DaoConfig offlineItemDaoConfig;

    private final DbBeanDao dbBeanDao;
    private final SearchHistoryDao searchHistoryDao;
    private final RecentItemDao recentItemDao;
    private final KvsDao kvsDao;
    private final OfflineItemDao offlineItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dbBeanDaoConfig = daoConfigMap.get(DbBeanDao.class).clone();
        dbBeanDaoConfig.initIdentityScope(type);

        searchHistoryDaoConfig = daoConfigMap.get(SearchHistoryDao.class).clone();
        searchHistoryDaoConfig.initIdentityScope(type);

        recentItemDaoConfig = daoConfigMap.get(RecentItemDao.class).clone();
        recentItemDaoConfig.initIdentityScope(type);

        kvsDaoConfig = daoConfigMap.get(KvsDao.class).clone();
        kvsDaoConfig.initIdentityScope(type);

        offlineItemDaoConfig = daoConfigMap.get(OfflineItemDao.class).clone();
        offlineItemDaoConfig.initIdentityScope(type);

        dbBeanDao = new DbBeanDao(dbBeanDaoConfig, this);
        searchHistoryDao = new SearchHistoryDao(searchHistoryDaoConfig, this);
        recentItemDao = new RecentItemDao(recentItemDaoConfig, this);
        kvsDao = new KvsDao(kvsDaoConfig, this);
        offlineItemDao = new OfflineItemDao(offlineItemDaoConfig, this);

        registerDao(DbBean.class, dbBeanDao);
        registerDao(SearchHistory.class, searchHistoryDao);
        registerDao(RecentItem.class, recentItemDao);
        registerDao(Kvs.class, kvsDao);
        registerDao(OfflineItem.class, offlineItemDao);
    }
    
    public void clear() {
        dbBeanDaoConfig.getIdentityScope().clear();
        searchHistoryDaoConfig.getIdentityScope().clear();
        recentItemDaoConfig.getIdentityScope().clear();
        kvsDaoConfig.getIdentityScope().clear();
        offlineItemDaoConfig.getIdentityScope().clear();
    }

    public DbBeanDao getDbBeanDao() {
        return dbBeanDao;
    }

    public SearchHistoryDao getSearchHistoryDao() {
        return searchHistoryDao;
    }

    public RecentItemDao getRecentItemDao() {
        return recentItemDao;
    }

    public KvsDao getKvsDao() {
        return kvsDao;
    }

    public OfflineItemDao getOfflineItemDao() {
        return offlineItemDao;
    }

}
