package com.pw.box.core.db.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DB_BEAN".
 */
public class DbBean {

    private Long id;
    private byte[] data;

    public DbBean() {
    }

    public DbBean(Long id) {
        this.id = id;
    }

    public DbBean(Long id, byte[] data) {
        this.id = id;
        this.data = data;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public byte[] getData() {
        return data;
    }

    public void setData(byte[] data) {
        this.data = data;
    }

}
