package com.pw.box.core.db.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "OFFLINE_ITEM".
 */
public class OfflineItem {

    private Long id;
    private String account;
    private String desc;
    private byte[] content;
    private byte[] salt;
    private Boolean havePassword;

    public OfflineItem() {
    }

    public OfflineItem(Long id) {
        this.id = id;
    }

    public OfflineItem(Long id, String account, String desc, byte[] content, byte[] salt, Boolean havePassword) {
        this.id = id;
        this.account = account;
        this.desc = desc;
        this.content = content;
        this.salt = salt;
        this.havePassword = havePassword;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public byte[] getContent() {
        return content;
    }

    public void setContent(byte[] content) {
        this.content = content;
    }

    public byte[] getSalt() {
        return salt;
    }

    public void setSalt(byte[] salt) {
        this.salt = salt;
    }

    public Boolean getHavePassword() {
        return havePassword;
    }

    public void setHavePassword(Boolean havePassword) {
        this.havePassword = havePassword;
    }

}
