package com.pw.box.core.db.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SEARCH_HISTORY".
 */
public class SearchHistory {

    private Long id;
    private String content;
    private Integer type;
    private Long time;

    public SearchHistory() {
    }

    public SearchHistory(Long id) {
        this.id = id;
    }

    public SearchHistory(Long id, String content, Integer type, Long time) {
        this.id = id;
        this.content = content;
        this.type = type;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

}
