//// Generated by the protocol buffer compiler.  DO NOT EDIT!
//// source: C.proto
//
//package com.pw.box;
//
//public final class C {
//  private C() {}
//  public static void registerAllExtensions(
//      com.google.protobuf.ExtensionRegistry registry) {
//  }
//  public interface SaveKeyOrBuilder extends
//      // @@protoc_insertion_point(interface_extends:com.pw.box.SaveKey)
//      com.google.protobuf.MessageOrBuilder {
//
//    /**
//     * <code>optional int32 line_count = 1;</code>
//     */
//    boolean hasLineCount();
//    /**
//     * <code>optional int32 line_count = 1;</code>
//     */
//    int getLineCount();
//
//    /**
//     * <code>optional string key_md5 = 2;</code>
//     */
//    boolean hasKeyMd5();
//    /**
//     * <code>optional string key_md5 = 2;</code>
//     */
//    java.lang.String getKeyMd5();
//    /**
//     * <code>optional string key_md5 = 2;</code>
//     */
//    com.google.protobuf.ByteString
//        getKeyMd5Bytes();
//
//    /**
//     * <code>optional string account = 3;</code>
//     */
//    boolean hasAccount();
//    /**
//     * <code>optional string account = 3;</code>
//     */
//    java.lang.String getAccount();
//    /**
//     * <code>optional string account = 3;</code>
//     */
//    com.google.protobuf.ByteString
//        getAccountBytes();
//
//    /**
//     * <code>optional bytes pw1 = 4;</code>
//     */
//    boolean hasPw1();
//    /**
//     * <code>optional bytes pw1 = 4;</code>
//     */
//    com.google.protobuf.ByteString getPw1();
//
//    /**
//     * <code>optional bytes pw2 = 5;</code>
//     */
//    boolean hasPw2();
//    /**
//     * <code>optional bytes pw2 = 5;</code>
//     */
//    com.google.protobuf.ByteString getPw2();
//  }
//  /**
//   * Protobuf type {@code com.pw.box.SaveKey}
//   */
//  public static final class SaveKey extends
//      com.google.protobuf.GeneratedMessage implements
//      // @@protoc_insertion_point(message_implements:com.pw.box.SaveKey)
//      SaveKeyOrBuilder {
//    // Use SaveKey.newBuilder() to construct.
//    private SaveKey(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
//      super(builder);
//      this.unknownFields = builder.getUnknownFields();
//    }
//    private SaveKey(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }
//
//    private static final SaveKey defaultInstance;
//    public static SaveKey getDefaultInstance() {
//      return defaultInstance;
//    }
//
//    public SaveKey getDefaultInstanceForType() {
//      return defaultInstance;
//    }
//
//    private final com.google.protobuf.UnknownFieldSet unknownFields;
//    @java.lang.Override
//    public final com.google.protobuf.UnknownFieldSet
//        getUnknownFields() {
//      return this.unknownFields;
//    }
//    private SaveKey(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      initFields();
//      int mutable_bitField0_ = 0;
//      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
//          com.google.protobuf.UnknownFieldSet.newBuilder();
//      try {
//        boolean done = false;
//        while (!done) {
//          int tag = input.readTag();
//          switch (tag) {
//            case 0:
//              done = true;
//              break;
//            default: {
//              if (!parseUnknownField(input, unknownFields,
//                                     extensionRegistry, tag)) {
//                done = true;
//              }
//              break;
//            }
//            case 8: {
//              bitField0_ |= 0x00000001;
//              lineCount_ = input.readInt32();
//              break;
//            }
//            case 18: {
//              com.google.protobuf.ByteString bs = input.readBytes();
//              bitField0_ |= 0x00000002;
//              keyMd5_ = bs;
//              break;
//            }
//            case 26: {
//              com.google.protobuf.ByteString bs = input.readBytes();
//              bitField0_ |= 0x00000004;
//              account_ = bs;
//              break;
//            }
//            case 34: {
//              bitField0_ |= 0x00000008;
//              pw1_ = input.readBytes();
//              break;
//            }
//            case 42: {
//              bitField0_ |= 0x00000010;
//              pw2_ = input.readBytes();
//              break;
//            }
//          }
//        }
//      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//        throw e.setUnfinishedMessage(this);
//      } catch (java.io.IOException e) {
//        throw new com.google.protobuf.InvalidProtocolBufferException(
//            e.getMessage()).setUnfinishedMessage(this);
//      } finally {
//        this.unknownFields = unknownFields.build();
//        makeExtensionsImmutable();
//      }
//    }
//    public static final com.google.protobuf.Descriptors.Descriptor
//        getDescriptor() {
//      return com.pw.box.C.internal_static_com_pw_box_SaveKey_descriptor;
//    }
//
//    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
//        internalGetFieldAccessorTable() {
//      return com.pw.box.C.internal_static_com_pw_box_SaveKey_fieldAccessorTable
//          .ensureFieldAccessorsInitialized(
//              com.pw.box.C.SaveKey.class, com.pw.box.C.SaveKey.Builder.class);
//    }
//
//    public static com.google.protobuf.Parser<SaveKey> PARSER =
//        new com.google.protobuf.AbstractParser<SaveKey>() {
//      public SaveKey parsePartialFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws com.google.protobuf.InvalidProtocolBufferException {
//        return new SaveKey(input, extensionRegistry);
//      }
//    };
//
//    @java.lang.Override
//    public com.google.protobuf.Parser<SaveKey> getParserForType() {
//      return PARSER;
//    }
//
//    private int bitField0_;
//    public static final int LINE_COUNT_FIELD_NUMBER = 1;
//    private int lineCount_;
//    /**
//     * <code>optional int32 line_count = 1;</code>
//     */
//    public boolean hasLineCount() {
//      return ((bitField0_ & 0x00000001) == 0x00000001);
//    }
//    /**
//     * <code>optional int32 line_count = 1;</code>
//     */
//    public int getLineCount() {
//      return lineCount_;
//    }
//
//    public static final int KEY_MD5_FIELD_NUMBER = 2;
//    private java.lang.Object keyMd5_;
//    /**
//     * <code>optional string key_md5 = 2;</code>
//     */
//    public boolean hasKeyMd5() {
//      return ((bitField0_ & 0x00000002) == 0x00000002);
//    }
//    /**
//     * <code>optional string key_md5 = 2;</code>
//     */
//    public java.lang.String getKeyMd5() {
//      java.lang.Object ref = keyMd5_;
//      if (ref instanceof java.lang.String) {
//        return (java.lang.String) ref;
//      } else {
//        com.google.protobuf.ByteString bs =
//            (com.google.protobuf.ByteString) ref;
//        java.lang.String s = bs.toStringUtf8();
//        if (bs.isValidUtf8()) {
//          keyMd5_ = s;
//        }
//        return s;
//      }
//    }
//    /**
//     * <code>optional string key_md5 = 2;</code>
//     */
//    public com.google.protobuf.ByteString
//        getKeyMd5Bytes() {
//      java.lang.Object ref = keyMd5_;
//      if (ref instanceof java.lang.String) {
//        com.google.protobuf.ByteString b =
//            com.google.protobuf.ByteString.copyFromUtf8(
//                (java.lang.String) ref);
//        keyMd5_ = b;
//        return b;
//      } else {
//        return (com.google.protobuf.ByteString) ref;
//      }
//    }
//
//    public static final int ACCOUNT_FIELD_NUMBER = 3;
//    private java.lang.Object account_;
//    /**
//     * <code>optional string account = 3;</code>
//     */
//    public boolean hasAccount() {
//      return ((bitField0_ & 0x00000004) == 0x00000004);
//    }
//    /**
//     * <code>optional string account = 3;</code>
//     */
//    public java.lang.String getAccount() {
//      java.lang.Object ref = account_;
//      if (ref instanceof java.lang.String) {
//        return (java.lang.String) ref;
//      } else {
//        com.google.protobuf.ByteString bs =
//            (com.google.protobuf.ByteString) ref;
//        java.lang.String s = bs.toStringUtf8();
//        if (bs.isValidUtf8()) {
//          account_ = s;
//        }
//        return s;
//      }
//    }
//    /**
//     * <code>optional string account = 3;</code>
//     */
//    public com.google.protobuf.ByteString
//        getAccountBytes() {
//      java.lang.Object ref = account_;
//      if (ref instanceof java.lang.String) {
//        com.google.protobuf.ByteString b =
//            com.google.protobuf.ByteString.copyFromUtf8(
//                (java.lang.String) ref);
//        account_ = b;
//        return b;
//      } else {
//        return (com.google.protobuf.ByteString) ref;
//      }
//    }
//
//    public static final int PW1_FIELD_NUMBER = 4;
//    private com.google.protobuf.ByteString pw1_;
//    /**
//     * <code>optional bytes pw1 = 4;</code>
//     */
//    public boolean hasPw1() {
//      return ((bitField0_ & 0x00000008) == 0x00000008);
//    }
//    /**
//     * <code>optional bytes pw1 = 4;</code>
//     */
//    public com.google.protobuf.ByteString getPw1() {
//      return pw1_;
//    }
//
//    public static final int PW2_FIELD_NUMBER = 5;
//    private com.google.protobuf.ByteString pw2_;
//    /**
//     * <code>optional bytes pw2 = 5;</code>
//     */
//    public boolean hasPw2() {
//      return ((bitField0_ & 0x00000010) == 0x00000010);
//    }
//    /**
//     * <code>optional bytes pw2 = 5;</code>
//     */
//    public com.google.protobuf.ByteString getPw2() {
//      return pw2_;
//    }
//
//    private void initFields() {
//      lineCount_ = 0;
//      keyMd5_ = "";
//      account_ = "";
//      pw1_ = com.google.protobuf.ByteString.EMPTY;
//      pw2_ = com.google.protobuf.ByteString.EMPTY;
//    }
//    private byte memoizedIsInitialized = -1;
//    public final boolean isInitialized() {
//      byte isInitialized = memoizedIsInitialized;
//      if (isInitialized == 1) return true;
//      if (isInitialized == 0) return false;
//
//      memoizedIsInitialized = 1;
//      return true;
//    }
//
//    public void writeTo(com.google.protobuf.CodedOutputStream output)
//                        throws java.io.IOException {
//      getSerializedSize();
//      if (((bitField0_ & 0x00000001) == 0x00000001)) {
//        output.writeInt32(1, lineCount_);
//      }
//      if (((bitField0_ & 0x00000002) == 0x00000002)) {
//        output.writeBytes(2, getKeyMd5Bytes());
//      }
//      if (((bitField0_ & 0x00000004) == 0x00000004)) {
//        output.writeBytes(3, getAccountBytes());
//      }
//      if (((bitField0_ & 0x00000008) == 0x00000008)) {
//        output.writeBytes(4, pw1_);
//      }
//      if (((bitField0_ & 0x00000010) == 0x00000010)) {
//        output.writeBytes(5, pw2_);
//      }
//      getUnknownFields().writeTo(output);
//    }
//
//    private int memoizedSerializedSize = -1;
//    public int getSerializedSize() {
//      int size = memoizedSerializedSize;
//      if (size != -1) return size;
//
//      size = 0;
//      if (((bitField0_ & 0x00000001) == 0x00000001)) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeInt32Size(1, lineCount_);
//      }
//      if (((bitField0_ & 0x00000002) == 0x00000002)) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeBytesSize(2, getKeyMd5Bytes());
//      }
//      if (((bitField0_ & 0x00000004) == 0x00000004)) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeBytesSize(3, getAccountBytes());
//      }
//      if (((bitField0_ & 0x00000008) == 0x00000008)) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeBytesSize(4, pw1_);
//      }
//      if (((bitField0_ & 0x00000010) == 0x00000010)) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeBytesSize(5, pw2_);
//      }
//      size += getUnknownFields().getSerializedSize();
//      memoizedSerializedSize = size;
//      return size;
//    }
//
//    private static final long serialVersionUID = 0L;
//    @java.lang.Override
//    protected java.lang.Object writeReplace()
//        throws java.io.ObjectStreamException {
//      return super.writeReplace();
//    }
//
//    public static com.pw.box.C.SaveKey parseFrom(
//        com.google.protobuf.ByteString data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static com.pw.box.C.SaveKey parseFrom(
//        com.google.protobuf.ByteString data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static com.pw.box.C.SaveKey parseFrom(byte[] data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static com.pw.box.C.SaveKey parseFrom(
//        byte[] data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static com.pw.box.C.SaveKey parseFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return PARSER.parseFrom(input);
//    }
//    public static com.pw.box.C.SaveKey parseFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return PARSER.parseFrom(input, extensionRegistry);
//    }
//    public static com.pw.box.C.SaveKey parseDelimitedFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return PARSER.parseDelimitedFrom(input);
//    }
//    public static com.pw.box.C.SaveKey parseDelimitedFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return PARSER.parseDelimitedFrom(input, extensionRegistry);
//    }
//    public static com.pw.box.C.SaveKey parseFrom(
//        com.google.protobuf.CodedInputStream input)
//        throws java.io.IOException {
//      return PARSER.parseFrom(input);
//    }
//    public static com.pw.box.C.SaveKey parseFrom(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return PARSER.parseFrom(input, extensionRegistry);
//    }
//
//    public static Builder newBuilder() { return Builder.create(); }
//    public Builder newBuilderForType() { return newBuilder(); }
//    public static Builder newBuilder(com.pw.box.C.SaveKey prototype) {
//      return newBuilder().mergeFrom(prototype);
//    }
//    public Builder toBuilder() { return newBuilder(this); }
//
//    @java.lang.Override
//    protected Builder newBuilderForType(
//        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
//      Builder builder = new Builder(parent);
//      return builder;
//    }
//    /**
//     * Protobuf type {@code com.pw.box.SaveKey}
//     */
//    public static final class Builder extends
//        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
//        // @@protoc_insertion_point(builder_implements:com.pw.box.SaveKey)
//        com.pw.box.C.SaveKeyOrBuilder {
//      public static final com.google.protobuf.Descriptors.Descriptor
//          getDescriptor() {
//        return com.pw.box.C.internal_static_com_pw_box_SaveKey_descriptor;
//      }
//
//      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
//          internalGetFieldAccessorTable() {
//        return com.pw.box.C.internal_static_com_pw_box_SaveKey_fieldAccessorTable
//            .ensureFieldAccessorsInitialized(
//                com.pw.box.C.SaveKey.class, com.pw.box.C.SaveKey.Builder.class);
//      }
//
//      // Construct using com.pw.box.C.SaveKey.newBuilder()
//      private Builder() {
//        maybeForceBuilderInitialization();
//      }
//
//      private Builder(
//          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
//        super(parent);
//        maybeForceBuilderInitialization();
//      }
//      private void maybeForceBuilderInitialization() {
//        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
//        }
//      }
//      private static Builder create() {
//        return new Builder();
//      }
//
//      public Builder clear() {
//        super.clear();
//        lineCount_ = 0;
//        bitField0_ = (bitField0_ & ~0x00000001);
//        keyMd5_ = "";
//        bitField0_ = (bitField0_ & ~0x00000002);
//        account_ = "";
//        bitField0_ = (bitField0_ & ~0x00000004);
//        pw1_ = com.google.protobuf.ByteString.EMPTY;
//        bitField0_ = (bitField0_ & ~0x00000008);
//        pw2_ = com.google.protobuf.ByteString.EMPTY;
//        bitField0_ = (bitField0_ & ~0x00000010);
//        return this;
//      }
//
//      public Builder clone() {
//        return create().mergeFrom(buildPartial());
//      }
//
//      public com.google.protobuf.Descriptors.Descriptor
//          getDescriptorForType() {
//        return com.pw.box.C.internal_static_com_pw_box_SaveKey_descriptor;
//      }
//
//      public com.pw.box.C.SaveKey getDefaultInstanceForType() {
//        return com.pw.box.C.SaveKey.getDefaultInstance();
//      }
//
//      public com.pw.box.C.SaveKey build() {
//        com.pw.box.C.SaveKey result = buildPartial();
//        if (!result.isInitialized()) {
//          throw newUninitializedMessageException(result);
//        }
//        return result;
//      }
//
//      public com.pw.box.C.SaveKey buildPartial() {
//        com.pw.box.C.SaveKey result = new com.pw.box.C.SaveKey(this);
//        int from_bitField0_ = bitField0_;
//        int to_bitField0_ = 0;
//        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
//          to_bitField0_ |= 0x00000001;
//        }
//        result.lineCount_ = lineCount_;
//        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
//          to_bitField0_ |= 0x00000002;
//        }
//        result.keyMd5_ = keyMd5_;
//        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
//          to_bitField0_ |= 0x00000004;
//        }
//        result.account_ = account_;
//        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
//          to_bitField0_ |= 0x00000008;
//        }
//        result.pw1_ = pw1_;
//        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
//          to_bitField0_ |= 0x00000010;
//        }
//        result.pw2_ = pw2_;
//        result.bitField0_ = to_bitField0_;
//        onBuilt();
//        return result;
//      }
//
//      public Builder mergeFrom(com.google.protobuf.Message other) {
//        if (other instanceof com.pw.box.C.SaveKey) {
//          return mergeFrom((com.pw.box.C.SaveKey)other);
//        } else {
//          super.mergeFrom(other);
//          return this;
//        }
//      }
//
//      public Builder mergeFrom(com.pw.box.C.SaveKey other) {
//        if (other == com.pw.box.C.SaveKey.getDefaultInstance()) return this;
//        if (other.hasLineCount()) {
//          setLineCount(other.getLineCount());
//        }
//        if (other.hasKeyMd5()) {
//          bitField0_ |= 0x00000002;
//          keyMd5_ = other.keyMd5_;
//          onChanged();
//        }
//        if (other.hasAccount()) {
//          bitField0_ |= 0x00000004;
//          account_ = other.account_;
//          onChanged();
//        }
//        if (other.hasPw1()) {
//          setPw1(other.getPw1());
//        }
//        if (other.hasPw2()) {
//          setPw2(other.getPw2());
//        }
//        this.mergeUnknownFields(other.getUnknownFields());
//        return this;
//      }
//
//      public final boolean isInitialized() {
//        return true;
//      }
//
//      public Builder mergeFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws java.io.IOException {
//        com.pw.box.C.SaveKey parsedMessage = null;
//        try {
//          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
//        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//          parsedMessage = (com.pw.box.C.SaveKey) e.getUnfinishedMessage();
//          throw e;
//        } finally {
//          if (parsedMessage != null) {
//            mergeFrom(parsedMessage);
//          }
//        }
//        return this;
//      }
//      private int bitField0_;
//
//      private int lineCount_ ;
//      /**
//       * <code>optional int32 line_count = 1;</code>
//       */
//      public boolean hasLineCount() {
//        return ((bitField0_ & 0x00000001) == 0x00000001);
//      }
//      /**
//       * <code>optional int32 line_count = 1;</code>
//       */
//      public int getLineCount() {
//        return lineCount_;
//      }
//      /**
//       * <code>optional int32 line_count = 1;</code>
//       */
//      public Builder setLineCount(int value) {
//        bitField0_ |= 0x00000001;
//        lineCount_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional int32 line_count = 1;</code>
//       */
//      public Builder clearLineCount() {
//        bitField0_ = (bitField0_ & ~0x00000001);
//        lineCount_ = 0;
//        onChanged();
//        return this;
//      }
//
//      private java.lang.Object keyMd5_ = "";
//      /**
//       * <code>optional string key_md5 = 2;</code>
//       */
//      public boolean hasKeyMd5() {
//        return ((bitField0_ & 0x00000002) == 0x00000002);
//      }
//      /**
//       * <code>optional string key_md5 = 2;</code>
//       */
//      public java.lang.String getKeyMd5() {
//        java.lang.Object ref = keyMd5_;
//        if (!(ref instanceof java.lang.String)) {
//          com.google.protobuf.ByteString bs =
//              (com.google.protobuf.ByteString) ref;
//          java.lang.String s = bs.toStringUtf8();
//          if (bs.isValidUtf8()) {
//            keyMd5_ = s;
//          }
//          return s;
//        } else {
//          return (java.lang.String) ref;
//        }
//      }
//      /**
//       * <code>optional string key_md5 = 2;</code>
//       */
//      public com.google.protobuf.ByteString
//          getKeyMd5Bytes() {
//        java.lang.Object ref = keyMd5_;
//        if (ref instanceof String) {
//          com.google.protobuf.ByteString b =
//              com.google.protobuf.ByteString.copyFromUtf8(
//                  (java.lang.String) ref);
//          keyMd5_ = b;
//          return b;
//        } else {
//          return (com.google.protobuf.ByteString) ref;
//        }
//      }
//      /**
//       * <code>optional string key_md5 = 2;</code>
//       */
//      public Builder setKeyMd5(
//          java.lang.String value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  bitField0_ |= 0x00000002;
//        keyMd5_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional string key_md5 = 2;</code>
//       */
//      public Builder clearKeyMd5() {
//        bitField0_ = (bitField0_ & ~0x00000002);
//        keyMd5_ = getDefaultInstance().getKeyMd5();
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional string key_md5 = 2;</code>
//       */
//      public Builder setKeyMd5Bytes(
//          com.google.protobuf.ByteString value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  bitField0_ |= 0x00000002;
//        keyMd5_ = value;
//        onChanged();
//        return this;
//      }
//
//      private java.lang.Object account_ = "";
//      /**
//       * <code>optional string account = 3;</code>
//       */
//      public boolean hasAccount() {
//        return ((bitField0_ & 0x00000004) == 0x00000004);
//      }
//      /**
//       * <code>optional string account = 3;</code>
//       */
//      public java.lang.String getAccount() {
//        java.lang.Object ref = account_;
//        if (!(ref instanceof java.lang.String)) {
//          com.google.protobuf.ByteString bs =
//              (com.google.protobuf.ByteString) ref;
//          java.lang.String s = bs.toStringUtf8();
//          if (bs.isValidUtf8()) {
//            account_ = s;
//          }
//          return s;
//        } else {
//          return (java.lang.String) ref;
//        }
//      }
//      /**
//       * <code>optional string account = 3;</code>
//       */
//      public com.google.protobuf.ByteString
//          getAccountBytes() {
//        java.lang.Object ref = account_;
//        if (ref instanceof String) {
//          com.google.protobuf.ByteString b =
//              com.google.protobuf.ByteString.copyFromUtf8(
//                  (java.lang.String) ref);
//          account_ = b;
//          return b;
//        } else {
//          return (com.google.protobuf.ByteString) ref;
//        }
//      }
//      /**
//       * <code>optional string account = 3;</code>
//       */
//      public Builder setAccount(
//          java.lang.String value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  bitField0_ |= 0x00000004;
//        account_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional string account = 3;</code>
//       */
//      public Builder clearAccount() {
//        bitField0_ = (bitField0_ & ~0x00000004);
//        account_ = getDefaultInstance().getAccount();
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional string account = 3;</code>
//       */
//      public Builder setAccountBytes(
//          com.google.protobuf.ByteString value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  bitField0_ |= 0x00000004;
//        account_ = value;
//        onChanged();
//        return this;
//      }
//
//      private com.google.protobuf.ByteString pw1_ = com.google.protobuf.ByteString.EMPTY;
//      /**
//       * <code>optional bytes pw1 = 4;</code>
//       */
//      public boolean hasPw1() {
//        return ((bitField0_ & 0x00000008) == 0x00000008);
//      }
//      /**
//       * <code>optional bytes pw1 = 4;</code>
//       */
//      public com.google.protobuf.ByteString getPw1() {
//        return pw1_;
//      }
//      /**
//       * <code>optional bytes pw1 = 4;</code>
//       */
//      public Builder setPw1(com.google.protobuf.ByteString value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  bitField0_ |= 0x00000008;
//        pw1_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional bytes pw1 = 4;</code>
//       */
//      public Builder clearPw1() {
//        bitField0_ = (bitField0_ & ~0x00000008);
//        pw1_ = getDefaultInstance().getPw1();
//        onChanged();
//        return this;
//      }
//
//      private com.google.protobuf.ByteString pw2_ = com.google.protobuf.ByteString.EMPTY;
//      /**
//       * <code>optional bytes pw2 = 5;</code>
//       */
//      public boolean hasPw2() {
//        return ((bitField0_ & 0x00000010) == 0x00000010);
//      }
//      /**
//       * <code>optional bytes pw2 = 5;</code>
//       */
//      public com.google.protobuf.ByteString getPw2() {
//        return pw2_;
//      }
//      /**
//       * <code>optional bytes pw2 = 5;</code>
//       */
//      public Builder setPw2(com.google.protobuf.ByteString value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  bitField0_ |= 0x00000010;
//        pw2_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional bytes pw2 = 5;</code>
//       */
//      public Builder clearPw2() {
//        bitField0_ = (bitField0_ & ~0x00000010);
//        pw2_ = getDefaultInstance().getPw2();
//        onChanged();
//        return this;
//      }
//
//      // @@protoc_insertion_point(builder_scope:com.pw.box.SaveKey)
//    }
//
//    static {
//      defaultInstance = new SaveKey(true);
//      defaultInstance.initFields();
//    }
//
//    // @@protoc_insertion_point(class_scope:com.pw.box.SaveKey)
//  }
//
//  private static final com.google.protobuf.Descriptors.Descriptor
//    internal_static_com_pw_box_SaveKey_descriptor;
//  private static
//    com.google.protobuf.GeneratedMessage.FieldAccessorTable
//      internal_static_com_pw_box_SaveKey_fieldAccessorTable;
//
//  public static com.google.protobuf.Descriptors.FileDescriptor
//      getDescriptor() {
//    return descriptor;
//  }
//  private static com.google.protobuf.Descriptors.FileDescriptor
//      descriptor;
//  static {
//    java.lang.String[] descriptorData = {
//      "\n\007C.proto\022\ncom.pw.box\"Y\n\007SaveKey\022\022\n\nline" +
//      "_count\030\001 \001(\005\022\017\n\007key_md5\030\002 \001(\t\022\017\n\007account" +
//      "\030\003 \001(\t\022\013\n\003pw1\030\004 \001(\014\022\013\n\003pw2\030\005 \001(\014"
//    };
//    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
//        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
//          public com.google.protobuf.ExtensionRegistry assignDescriptors(
//              com.google.protobuf.Descriptors.FileDescriptor root) {
//            descriptor = root;
//            return null;
//          }
//        };
//    com.google.protobuf.Descriptors.FileDescriptor
//      .internalBuildGeneratedFileFrom(descriptorData,
//        new com.google.protobuf.Descriptors.FileDescriptor[] {
//        }, assigner);
//    internal_static_com_pw_box_SaveKey_descriptor =
//      getDescriptor().getMessageTypes().get(0);
//    internal_static_com_pw_box_SaveKey_fieldAccessorTable = new
//      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
//        internal_static_com_pw_box_SaveKey_descriptor,
//        new java.lang.String[] { "LineCount", "KeyMd5", "Account", "Pw1", "Pw2", });
//  }
//
//  // @@protoc_insertion_point(outer_class_scope)
//}
