// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: pwbox.proto at 178:1
package com.pw.box.bean.protobuf;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * 用于请求分组列表的返回,新增分组
 */
public final class AddGroupResponse extends Message<AddGroupResponse, AddGroupResponse.Builder> {
  public static final ProtoAdapter<AddGroupResponse> ADAPTER = new ProtoAdapter_AddGroupResponse();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_RETCODE = 0;

  public static final String DEFAULT_DESCRIPTION = "";

  public static final Integer DEFAULT_ID = 0;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer retCode;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String description;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer id;

  public AddGroupResponse(Integer retCode, String description, Integer id) {
    this(retCode, description, id, ByteString.EMPTY);
  }

  public AddGroupResponse(Integer retCode, String description, Integer id, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.retCode = retCode;
    this.description = description;
    this.id = id;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.retCode = retCode;
    builder.description = description;
    builder.id = id;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof AddGroupResponse)) return false;
    AddGroupResponse o = (AddGroupResponse) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(retCode, o.retCode)
        && Internal.equals(description, o.description)
        && Internal.equals(id, o.id);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (retCode != null ? retCode.hashCode() : 0);
      result = result * 37 + (description != null ? description.hashCode() : 0);
      result = result * 37 + (id != null ? id.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (retCode != null) builder.append(", retCode=").append(retCode);
    if (description != null) builder.append(", description=").append(description);
    if (id != null) builder.append(", id=").append(id);
    return builder.replace(0, 2, "AddGroupResponse{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<AddGroupResponse, Builder> {
    public Integer retCode;

    public String description;

    public Integer id;

    public Builder() {
    }

    public Builder retCode(Integer retCode) {
      this.retCode = retCode;
      return this;
    }

    public Builder description(String description) {
      this.description = description;
      return this;
    }

    public Builder id(Integer id) {
      this.id = id;
      return this;
    }

    @Override
    public AddGroupResponse build() {
      return new AddGroupResponse(retCode, description, id, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_AddGroupResponse extends ProtoAdapter<AddGroupResponse> {
    ProtoAdapter_AddGroupResponse() {
      super(FieldEncoding.LENGTH_DELIMITED, AddGroupResponse.class);
    }

    @Override
    public int encodedSize(AddGroupResponse value) {
      return (value.retCode != null ? ProtoAdapter.INT32.encodedSizeWithTag(1, value.retCode) : 0)
          + (value.description != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.description) : 0)
          + (value.id != null ? ProtoAdapter.INT32.encodedSizeWithTag(3, value.id) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, AddGroupResponse value) throws IOException {
      if (value.retCode != null) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.retCode);
      if (value.description != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.description);
      if (value.id != null) ProtoAdapter.INT32.encodeWithTag(writer, 3, value.id);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public AddGroupResponse decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.retCode(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.description(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.id(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public AddGroupResponse redact(AddGroupResponse value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
