// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: pwbox.proto at 173:1
package com.pw.box.bean.protobuf;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * 用于请求分组列表的返回,新增分组
 */
public final class AddGroupRequest extends Message<AddGroupRequest, AddGroupRequest.Builder> {
  public static final ProtoAdapter<AddGroupRequest> ADAPTER = new ProtoAdapter_AddGroupRequest();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_NAME = "";

  public static final String DEFAULT_DESC = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String name;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String desc;

  public AddGroupRequest(String name, String desc) {
    this(name, desc, ByteString.EMPTY);
  }

  public AddGroupRequest(String name, String desc, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.name = name;
    this.desc = desc;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.name = name;
    builder.desc = desc;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof AddGroupRequest)) return false;
    AddGroupRequest o = (AddGroupRequest) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(name, o.name)
        && Internal.equals(desc, o.desc);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (name != null ? name.hashCode() : 0);
      result = result * 37 + (desc != null ? desc.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (name != null) builder.append(", name=").append(name);
    if (desc != null) builder.append(", desc=").append(desc);
    return builder.replace(0, 2, "AddGroupRequest{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<AddGroupRequest, Builder> {
    public String name;

    public String desc;

    public Builder() {
    }

    public Builder name(String name) {
      this.name = name;
      return this;
    }

    public Builder desc(String desc) {
      this.desc = desc;
      return this;
    }

    @Override
    public AddGroupRequest build() {
      return new AddGroupRequest(name, desc, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_AddGroupRequest extends ProtoAdapter<AddGroupRequest> {
    ProtoAdapter_AddGroupRequest() {
      super(FieldEncoding.LENGTH_DELIMITED, AddGroupRequest.class);
    }

    @Override
    public int encodedSize(AddGroupRequest value) {
      return (value.name != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.name) : 0)
          + (value.desc != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.desc) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, AddGroupRequest value) throws IOException {
      if (value.name != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.name);
      if (value.desc != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.desc);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public AddGroupRequest decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.name(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.desc(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public AddGroupRequest redact(AddGroupRequest value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
