// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: pwbox.proto at 16:1
package com.pw.box.bean.protobuf;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class AppUpdateInfo extends Message<AppUpdateInfo, AppUpdateInfo.Builder> {
  public static final ProtoAdapter<AppUpdateInfo> ADAPTER = new ProtoAdapter_AppUpdateInfo();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_VERSION_CODE = 0;

  public static final String DEFAULT_VERSION_NAME = "";

  public static final String DEFAULT_DESC = "";

  public static final String DEFAULT_URL = "";

  public static final Integer DEFAULT_SIZE = 0;

  public static final String DEFAULT_MD5 = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer version_code;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String version_name;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String desc;

  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String url;

  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer size;

  @WireField(
      tag = 6,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String md5;

  public AppUpdateInfo(Integer version_code, String version_name, String desc, String url, Integer size, String md5) {
    this(version_code, version_name, desc, url, size, md5, ByteString.EMPTY);
  }

  public AppUpdateInfo(Integer version_code, String version_name, String desc, String url, Integer size, String md5, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.version_code = version_code;
    this.version_name = version_name;
    this.desc = desc;
    this.url = url;
    this.size = size;
    this.md5 = md5;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.version_code = version_code;
    builder.version_name = version_name;
    builder.desc = desc;
    builder.url = url;
    builder.size = size;
    builder.md5 = md5;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof AppUpdateInfo)) return false;
    AppUpdateInfo o = (AppUpdateInfo) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(version_code, o.version_code)
        && Internal.equals(version_name, o.version_name)
        && Internal.equals(desc, o.desc)
        && Internal.equals(url, o.url)
        && Internal.equals(size, o.size)
        && Internal.equals(md5, o.md5);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (version_code != null ? version_code.hashCode() : 0);
      result = result * 37 + (version_name != null ? version_name.hashCode() : 0);
      result = result * 37 + (desc != null ? desc.hashCode() : 0);
      result = result * 37 + (url != null ? url.hashCode() : 0);
      result = result * 37 + (size != null ? size.hashCode() : 0);
      result = result * 37 + (md5 != null ? md5.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (version_code != null) builder.append(", version_code=").append(version_code);
    if (version_name != null) builder.append(", version_name=").append(version_name);
    if (desc != null) builder.append(", desc=").append(desc);
    if (url != null) builder.append(", url=").append(url);
    if (size != null) builder.append(", size=").append(size);
    if (md5 != null) builder.append(", md5=").append(md5);
    return builder.replace(0, 2, "AppUpdateInfo{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<AppUpdateInfo, Builder> {
    public Integer version_code;

    public String version_name;

    public String desc;

    public String url;

    public Integer size;

    public String md5;

    public Builder() {
    }

    public Builder version_code(Integer version_code) {
      this.version_code = version_code;
      return this;
    }

    public Builder version_name(String version_name) {
      this.version_name = version_name;
      return this;
    }

    public Builder desc(String desc) {
      this.desc = desc;
      return this;
    }

    public Builder url(String url) {
      this.url = url;
      return this;
    }

    public Builder size(Integer size) {
      this.size = size;
      return this;
    }

    public Builder md5(String md5) {
      this.md5 = md5;
      return this;
    }

    @Override
    public AppUpdateInfo build() {
      return new AppUpdateInfo(version_code, version_name, desc, url, size, md5, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_AppUpdateInfo extends ProtoAdapter<AppUpdateInfo> {
    ProtoAdapter_AppUpdateInfo() {
      super(FieldEncoding.LENGTH_DELIMITED, AppUpdateInfo.class);
    }

    @Override
    public int encodedSize(AppUpdateInfo value) {
      return (value.version_code != null ? ProtoAdapter.INT32.encodedSizeWithTag(1, value.version_code) : 0)
          + (value.version_name != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.version_name) : 0)
          + (value.desc != null ? ProtoAdapter.STRING.encodedSizeWithTag(3, value.desc) : 0)
          + (value.url != null ? ProtoAdapter.STRING.encodedSizeWithTag(4, value.url) : 0)
          + (value.size != null ? ProtoAdapter.INT32.encodedSizeWithTag(5, value.size) : 0)
          + (value.md5 != null ? ProtoAdapter.STRING.encodedSizeWithTag(6, value.md5) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, AppUpdateInfo value) throws IOException {
      if (value.version_code != null) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.version_code);
      if (value.version_name != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.version_name);
      if (value.desc != null) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.desc);
      if (value.url != null) ProtoAdapter.STRING.encodeWithTag(writer, 4, value.url);
      if (value.size != null) ProtoAdapter.INT32.encodeWithTag(writer, 5, value.size);
      if (value.md5 != null) ProtoAdapter.STRING.encodeWithTag(writer, 6, value.md5);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public AppUpdateInfo decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.version_code(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.version_name(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.desc(ProtoAdapter.STRING.decode(reader)); break;
          case 4: builder.url(ProtoAdapter.STRING.decode(reader)); break;
          case 5: builder.size(ProtoAdapter.INT32.decode(reader)); break;
          case 6: builder.md5(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public AppUpdateInfo redact(AppUpdateInfo value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
