// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: pwbox.proto at 25:1
package com.pw.box.bean.protobuf;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class CheckAppVerRequest extends Message<CheckAppVerRequest, CheckAppVerRequest.Builder> {
  public static final ProtoAdapter<CheckAppVerRequest> ADAPTER = new ProtoAdapter_CheckAppVerRequest();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_VER = 0;

  public static final String DEFAULT_CHANNEL = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer ver;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String channel;

  public CheckAppVerRequest(Integer ver, String channel) {
    this(ver, channel, ByteString.EMPTY);
  }

  public CheckAppVerRequest(Integer ver, String channel, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.ver = ver;
    this.channel = channel;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.ver = ver;
    builder.channel = channel;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof CheckAppVerRequest)) return false;
    CheckAppVerRequest o = (CheckAppVerRequest) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(ver, o.ver)
        && Internal.equals(channel, o.channel);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (ver != null ? ver.hashCode() : 0);
      result = result * 37 + (channel != null ? channel.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (ver != null) builder.append(", ver=").append(ver);
    if (channel != null) builder.append(", channel=").append(channel);
    return builder.replace(0, 2, "CheckAppVerRequest{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<CheckAppVerRequest, Builder> {
    public Integer ver;

    public String channel;

    public Builder() {
    }

    public Builder ver(Integer ver) {
      this.ver = ver;
      return this;
    }

    public Builder channel(String channel) {
      this.channel = channel;
      return this;
    }

    @Override
    public CheckAppVerRequest build() {
      return new CheckAppVerRequest(ver, channel, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_CheckAppVerRequest extends ProtoAdapter<CheckAppVerRequest> {
    ProtoAdapter_CheckAppVerRequest() {
      super(FieldEncoding.LENGTH_DELIMITED, CheckAppVerRequest.class);
    }

    @Override
    public int encodedSize(CheckAppVerRequest value) {
      return (value.ver != null ? ProtoAdapter.INT32.encodedSizeWithTag(1, value.ver) : 0)
          + (value.channel != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.channel) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, CheckAppVerRequest value) throws IOException {
      if (value.ver != null) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.ver);
      if (value.channel != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.channel);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public CheckAppVerRequest decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.ver(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.channel(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public CheckAppVerRequest redact(CheckAppVerRequest value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
