// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: pwbox.proto at 30:1
package com.pw.box.bean.protobuf;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class CheckAppVerResponse extends Message<CheckAppVerResponse, CheckAppVerResponse.Builder> {
  public static final ProtoAdapter<CheckAppVerResponse> ADAPTER = new ProtoAdapter_CheckAppVerResponse();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_RETCODE = 0;

  public static final String DEFAULT_ERRORMESSAGE = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer retCode;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String errorMessage;

  @WireField(
      tag = 3,
      adapter = "com.pw.box.bean.protobuf.AppUpdateInfo#ADAPTER"
  )
  public final AppUpdateInfo info;

  public CheckAppVerResponse(Integer retCode, String errorMessage, AppUpdateInfo info) {
    this(retCode, errorMessage, info, ByteString.EMPTY);
  }

  public CheckAppVerResponse(Integer retCode, String errorMessage, AppUpdateInfo info, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.retCode = retCode;
    this.errorMessage = errorMessage;
    this.info = info;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.retCode = retCode;
    builder.errorMessage = errorMessage;
    builder.info = info;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof CheckAppVerResponse)) return false;
    CheckAppVerResponse o = (CheckAppVerResponse) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(retCode, o.retCode)
        && Internal.equals(errorMessage, o.errorMessage)
        && Internal.equals(info, o.info);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (retCode != null ? retCode.hashCode() : 0);
      result = result * 37 + (errorMessage != null ? errorMessage.hashCode() : 0);
      result = result * 37 + (info != null ? info.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (retCode != null) builder.append(", retCode=").append(retCode);
    if (errorMessage != null) builder.append(", errorMessage=").append(errorMessage);
    if (info != null) builder.append(", info=").append(info);
    return builder.replace(0, 2, "CheckAppVerResponse{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<CheckAppVerResponse, Builder> {
    public Integer retCode;

    public String errorMessage;

    public AppUpdateInfo info;

    public Builder() {
    }

    public Builder retCode(Integer retCode) {
      this.retCode = retCode;
      return this;
    }

    public Builder errorMessage(String errorMessage) {
      this.errorMessage = errorMessage;
      return this;
    }

    public Builder info(AppUpdateInfo info) {
      this.info = info;
      return this;
    }

    @Override
    public CheckAppVerResponse build() {
      return new CheckAppVerResponse(retCode, errorMessage, info, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_CheckAppVerResponse extends ProtoAdapter<CheckAppVerResponse> {
    ProtoAdapter_CheckAppVerResponse() {
      super(FieldEncoding.LENGTH_DELIMITED, CheckAppVerResponse.class);
    }

    @Override
    public int encodedSize(CheckAppVerResponse value) {
      return (value.retCode != null ? ProtoAdapter.INT32.encodedSizeWithTag(1, value.retCode) : 0)
          + (value.errorMessage != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.errorMessage) : 0)
          + (value.info != null ? AppUpdateInfo.ADAPTER.encodedSizeWithTag(3, value.info) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, CheckAppVerResponse value) throws IOException {
      if (value.retCode != null) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.retCode);
      if (value.errorMessage != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.errorMessage);
      if (value.info != null) AppUpdateInfo.ADAPTER.encodeWithTag(writer, 3, value.info);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public CheckAppVerResponse decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.retCode(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.errorMessage(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.info(AppUpdateInfo.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public CheckAppVerResponse redact(CheckAppVerResponse value) {
      Builder builder = value.newBuilder();
      if (builder.info != null) builder.info = AppUpdateInfo.ADAPTER.redact(builder.info);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
