// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: pwbox.proto at 143:1
package com.pw.box.bean.protobuf;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

public final class DeleteItemReq extends Message<DeleteItemReq, DeleteItemReq.Builder> {
  public static final ProtoAdapter<DeleteItemReq> ADAPTER = new ProtoAdapter_DeleteItemReq();

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT64",
      label = WireField.Label.REPEATED
  )
  public final List<Long> id;

  public DeleteItemReq(List<Long> id) {
    this(id, ByteString.EMPTY);
  }

  public DeleteItemReq(List<Long> id, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.id = Internal.immutableCopyOf("id", id);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.id = Internal.copyOf("id", id);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof DeleteItemReq)) return false;
    DeleteItemReq o = (DeleteItemReq) other;
    return unknownFields().equals(o.unknownFields())
        && id.equals(o.id);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + id.hashCode();
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (!id.isEmpty()) builder.append(", id=").append(id);
    return builder.replace(0, 2, "DeleteItemReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<DeleteItemReq, Builder> {
    public List<Long> id;

    public Builder() {
      id = Internal.newMutableList();
    }

    public Builder id(List<Long> id) {
      Internal.checkElementsNotNull(id);
      this.id = id;
      return this;
    }

    @Override
    public DeleteItemReq build() {
      return new DeleteItemReq(id, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_DeleteItemReq extends ProtoAdapter<DeleteItemReq> {
    ProtoAdapter_DeleteItemReq() {
      super(FieldEncoding.LENGTH_DELIMITED, DeleteItemReq.class);
    }

    @Override
    public int encodedSize(DeleteItemReq value) {
      return ProtoAdapter.INT64.asRepeated().encodedSizeWithTag(1, value.id)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, DeleteItemReq value) throws IOException {
      ProtoAdapter.INT64.asRepeated().encodeWithTag(writer, 1, value.id);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public DeleteItemReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.id.add(ProtoAdapter.INT64.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public DeleteItemReq redact(DeleteItemReq value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
