// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: pwbox.proto at 188:1
package com.pw.box.bean.protobuf;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class EditGroupRequest extends Message<EditGroupRequest, EditGroupRequest.Builder> {
  public static final ProtoAdapter<EditGroupRequest> ADAPTER = new ProtoAdapter_EditGroupRequest();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_ID = 0;

  public static final String DEFAULT_NAME = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer id;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String name;

  public EditGroupRequest(Integer id, String name) {
    this(id, name, ByteString.EMPTY);
  }

  public EditGroupRequest(Integer id, String name, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.id = id;
    this.name = name;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.id = id;
    builder.name = name;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof EditGroupRequest)) return false;
    EditGroupRequest o = (EditGroupRequest) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(id, o.id)
        && Internal.equals(name, o.name);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (id != null ? id.hashCode() : 0);
      result = result * 37 + (name != null ? name.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (id != null) builder.append(", id=").append(id);
    if (name != null) builder.append(", name=").append(name);
    return builder.replace(0, 2, "EditGroupRequest{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<EditGroupRequest, Builder> {
    public Integer id;

    public String name;

    public Builder() {
    }

    public Builder id(Integer id) {
      this.id = id;
      return this;
    }

    public Builder name(String name) {
      this.name = name;
      return this;
    }

    @Override
    public EditGroupRequest build() {
      return new EditGroupRequest(id, name, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_EditGroupRequest extends ProtoAdapter<EditGroupRequest> {
    ProtoAdapter_EditGroupRequest() {
      super(FieldEncoding.LENGTH_DELIMITED, EditGroupRequest.class);
    }

    @Override
    public int encodedSize(EditGroupRequest value) {
      return (value.id != null ? ProtoAdapter.INT32.encodedSizeWithTag(1, value.id) : 0)
          + (value.name != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.name) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, EditGroupRequest value) throws IOException {
      if (value.id != null) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.id);
      if (value.name != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.name);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public EditGroupRequest decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.id(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.name(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public EditGroupRequest redact(EditGroupRequest value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
