// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: pwbox.proto at 166:1
package com.pw.box.bean.protobuf;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

/**
 * 用于请求分组列表的返回,新增分组
 */
public final class GetGroupListResponse extends Message<GetGroupListResponse, GetGroupListResponse.Builder> {
  public static final ProtoAdapter<GetGroupListResponse> ADAPTER = new ProtoAdapter_GetGroupListResponse();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_RETCODE = 0;

  public static final String DEFAULT_DESCRIPTION = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer retCode;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String description;

  @WireField(
      tag = 3,
      adapter = "com.pw.box.bean.protobuf.Group#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<Group> gps;

  public GetGroupListResponse(Integer retCode, String description, List<Group> gps) {
    this(retCode, description, gps, ByteString.EMPTY);
  }

  public GetGroupListResponse(Integer retCode, String description, List<Group> gps, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.retCode = retCode;
    this.description = description;
    this.gps = Internal.immutableCopyOf("gps", gps);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.retCode = retCode;
    builder.description = description;
    builder.gps = Internal.copyOf("gps", gps);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetGroupListResponse)) return false;
    GetGroupListResponse o = (GetGroupListResponse) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(retCode, o.retCode)
        && Internal.equals(description, o.description)
        && gps.equals(o.gps);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (retCode != null ? retCode.hashCode() : 0);
      result = result * 37 + (description != null ? description.hashCode() : 0);
      result = result * 37 + gps.hashCode();
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (retCode != null) builder.append(", retCode=").append(retCode);
    if (description != null) builder.append(", description=").append(description);
    if (!gps.isEmpty()) builder.append(", gps=").append(gps);
    return builder.replace(0, 2, "GetGroupListResponse{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GetGroupListResponse, Builder> {
    public Integer retCode;

    public String description;

    public List<Group> gps;

    public Builder() {
      gps = Internal.newMutableList();
    }

    public Builder retCode(Integer retCode) {
      this.retCode = retCode;
      return this;
    }

    public Builder description(String description) {
      this.description = description;
      return this;
    }

    public Builder gps(List<Group> gps) {
      Internal.checkElementsNotNull(gps);
      this.gps = gps;
      return this;
    }

    @Override
    public GetGroupListResponse build() {
      return new GetGroupListResponse(retCode, description, gps, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetGroupListResponse extends ProtoAdapter<GetGroupListResponse> {
    ProtoAdapter_GetGroupListResponse() {
      super(FieldEncoding.LENGTH_DELIMITED, GetGroupListResponse.class);
    }

    @Override
    public int encodedSize(GetGroupListResponse value) {
      return (value.retCode != null ? ProtoAdapter.INT32.encodedSizeWithTag(1, value.retCode) : 0)
          + (value.description != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.description) : 0)
          + Group.ADAPTER.asRepeated().encodedSizeWithTag(3, value.gps)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, GetGroupListResponse value) throws IOException {
      if (value.retCode != null) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.retCode);
      if (value.description != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.description);
      Group.ADAPTER.asRepeated().encodeWithTag(writer, 3, value.gps);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetGroupListResponse decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.retCode(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.description(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.gps.add(Group.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public GetGroupListResponse redact(GetGroupListResponse value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.gps, Group.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
