// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: pwbox.proto at 161:1
package com.pw.box.bean.protobuf;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * 用于请求分组列表的返回,新增分组
 */
public final class GetGroupListRequest extends Message<GetGroupListRequest, GetGroupListRequest.Builder> {
  public static final ProtoAdapter<GetGroupListRequest> ADAPTER = new ProtoAdapter_GetGroupListRequest();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_MD5 = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String md5;

  public GetGroupListRequest(String md5) {
    this(md5, ByteString.EMPTY);
  }

  public GetGroupListRequest(String md5, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.md5 = md5;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.md5 = md5;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetGroupListRequest)) return false;
    GetGroupListRequest o = (GetGroupListRequest) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(md5, o.md5);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (md5 != null ? md5.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (md5 != null) builder.append(", md5=").append(md5);
    return builder.replace(0, 2, "GetGroupListRequest{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GetGroupListRequest, Builder> {
    public String md5;

    public Builder() {
    }

    public Builder md5(String md5) {
      this.md5 = md5;
      return this;
    }

    @Override
    public GetGroupListRequest build() {
      return new GetGroupListRequest(md5, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetGroupListRequest extends ProtoAdapter<GetGroupListRequest> {
    ProtoAdapter_GetGroupListRequest() {
      super(FieldEncoding.LENGTH_DELIMITED, GetGroupListRequest.class);
    }

    @Override
    public int encodedSize(GetGroupListRequest value) {
      return (value.md5 != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.md5) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, GetGroupListRequest value) throws IOException {
      if (value.md5 != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.md5);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetGroupListRequest decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.md5(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public GetGroupListRequest redact(GetGroupListRequest value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
