// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: pwbox.proto at 9:1
package com.pw.box.bean.protobuf;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class GetHostRes extends Message<GetHostRes, GetHostRes.Builder> {
  public static final ProtoAdapter<GetHostRes> ADAPTER = new ProtoAdapter_GetHostRes();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_RETCODE = 0;

  public static final String DEFAULT_ERRORMESSAGE = "";

  public static final String DEFAULT_HOST = "";

  public static final Integer DEFAULT_PORT = 0;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer retCode;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String errorMessage;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String host;

  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer port;

  public GetHostRes(Integer retCode, String errorMessage, String host, Integer port) {
    this(retCode, errorMessage, host, port, ByteString.EMPTY);
  }

  public GetHostRes(Integer retCode, String errorMessage, String host, Integer port, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.retCode = retCode;
    this.errorMessage = errorMessage;
    this.host = host;
    this.port = port;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.retCode = retCode;
    builder.errorMessage = errorMessage;
    builder.host = host;
    builder.port = port;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetHostRes)) return false;
    GetHostRes o = (GetHostRes) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(retCode, o.retCode)
        && Internal.equals(errorMessage, o.errorMessage)
        && Internal.equals(host, o.host)
        && Internal.equals(port, o.port);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (retCode != null ? retCode.hashCode() : 0);
      result = result * 37 + (errorMessage != null ? errorMessage.hashCode() : 0);
      result = result * 37 + (host != null ? host.hashCode() : 0);
      result = result * 37 + (port != null ? port.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (retCode != null) builder.append(", retCode=").append(retCode);
    if (errorMessage != null) builder.append(", errorMessage=").append(errorMessage);
    if (host != null) builder.append(", host=").append(host);
    if (port != null) builder.append(", port=").append(port);
    return builder.replace(0, 2, "GetHostRes{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GetHostRes, Builder> {
    public Integer retCode;

    public String errorMessage;

    public String host;

    public Integer port;

    public Builder() {
    }

    public Builder retCode(Integer retCode) {
      this.retCode = retCode;
      return this;
    }

    public Builder errorMessage(String errorMessage) {
      this.errorMessage = errorMessage;
      return this;
    }

    public Builder host(String host) {
      this.host = host;
      return this;
    }

    public Builder port(Integer port) {
      this.port = port;
      return this;
    }

    @Override
    public GetHostRes build() {
      return new GetHostRes(retCode, errorMessage, host, port, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetHostRes extends ProtoAdapter<GetHostRes> {
    ProtoAdapter_GetHostRes() {
      super(FieldEncoding.LENGTH_DELIMITED, GetHostRes.class);
    }

    @Override
    public int encodedSize(GetHostRes value) {
      return (value.retCode != null ? ProtoAdapter.INT32.encodedSizeWithTag(1, value.retCode) : 0)
          + (value.errorMessage != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.errorMessage) : 0)
          + (value.host != null ? ProtoAdapter.STRING.encodedSizeWithTag(3, value.host) : 0)
          + (value.port != null ? ProtoAdapter.INT32.encodedSizeWithTag(4, value.port) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, GetHostRes value) throws IOException {
      if (value.retCode != null) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.retCode);
      if (value.errorMessage != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.errorMessage);
      if (value.host != null) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.host);
      if (value.port != null) ProtoAdapter.INT32.encodeWithTag(writer, 4, value.port);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetHostRes decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.retCode(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.errorMessage(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.host(ProtoAdapter.STRING.decode(reader)); break;
          case 4: builder.port(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public GetHostRes redact(GetHostRes value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
