// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: pwbox.proto at 129:1
package com.pw.box.bean.protobuf;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class GetItemListReq extends Message<GetItemListReq, GetItemListReq.Builder> {
  public static final ProtoAdapter<GetItemListReq> ADAPTER = new ProtoAdapter_GetItemListReq();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_V = 0;

  public static final Long DEFAULT_FROM = 0L;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer v;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long from;

  public GetItemListReq(Integer v, Long from) {
    this(v, from, ByteString.EMPTY);
  }

  public GetItemListReq(Integer v, Long from, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.v = v;
    this.from = from;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.v = v;
    builder.from = from;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetItemListReq)) return false;
    GetItemListReq o = (GetItemListReq) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(v, o.v)
        && Internal.equals(from, o.from);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (v != null ? v.hashCode() : 0);
      result = result * 37 + (from != null ? from.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (v != null) builder.append(", v=").append(v);
    if (from != null) builder.append(", from=").append(from);
    return builder.replace(0, 2, "GetItemListReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GetItemListReq, Builder> {
    public Integer v;

    public Long from;

    public Builder() {
    }

    public Builder v(Integer v) {
      this.v = v;
      return this;
    }

    public Builder from(Long from) {
      this.from = from;
      return this;
    }

    @Override
    public GetItemListReq build() {
      return new GetItemListReq(v, from, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetItemListReq extends ProtoAdapter<GetItemListReq> {
    ProtoAdapter_GetItemListReq() {
      super(FieldEncoding.LENGTH_DELIMITED, GetItemListReq.class);
    }

    @Override
    public int encodedSize(GetItemListReq value) {
      return (value.v != null ? ProtoAdapter.INT32.encodedSizeWithTag(1, value.v) : 0)
          + (value.from != null ? ProtoAdapter.INT64.encodedSizeWithTag(2, value.from) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, GetItemListReq value) throws IOException {
      if (value.v != null) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.v);
      if (value.from != null) ProtoAdapter.INT64.encodeWithTag(writer, 2, value.from);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetItemListReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.v(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.from(ProtoAdapter.INT64.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public GetItemListReq redact(GetItemListReq value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
