// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: pwbox.proto at 70:1
package com.pw.box.bean.protobuf;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class GetProtecReq extends Message<GetProtecReq, GetProtecReq.Builder> {
  public static final ProtoAdapter<GetProtecReq> ADAPTER = new ProtoAdapter_GetProtecReq();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_ACCOUNT = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String account;

  public GetProtecReq(String account) {
    this(account, ByteString.EMPTY);
  }

  public GetProtecReq(String account, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.account = account;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.account = account;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetProtecReq)) return false;
    GetProtecReq o = (GetProtecReq) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(account, o.account);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (account != null ? account.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (account != null) builder.append(", account=").append(account);
    return builder.replace(0, 2, "GetProtecReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GetProtecReq, Builder> {
    public String account;

    public Builder() {
    }

    public Builder account(String account) {
      this.account = account;
      return this;
    }

    @Override
    public GetProtecReq build() {
      return new GetProtecReq(account, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetProtecReq extends ProtoAdapter<GetProtecReq> {
    ProtoAdapter_GetProtecReq() {
      super(FieldEncoding.LENGTH_DELIMITED, GetProtecReq.class);
    }

    @Override
    public int encodedSize(GetProtecReq value) {
      return (value.account != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.account) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, GetProtecReq value) throws IOException {
      if (value.account != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.account);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetProtecReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.account(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public GetProtecReq redact(GetProtecReq value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
