// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: pwbox.proto at 184:1
package com.pw.box.bean.protobuf;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

public final class IntList extends Message<IntList, IntList.Builder> {
  public static final ProtoAdapter<IntList> ADAPTER = new ProtoAdapter_IntList();

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32",
      label = WireField.Label.REPEATED
  )
  public final List<Integer> ids;

  public IntList(List<Integer> ids) {
    this(ids, ByteString.EMPTY);
  }

  public IntList(List<Integer> ids, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.ids = Internal.immutableCopyOf("ids", ids);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.ids = Internal.copyOf("ids", ids);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof IntList)) return false;
    IntList o = (IntList) other;
    return unknownFields().equals(o.unknownFields())
        && ids.equals(o.ids);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + ids.hashCode();
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (!ids.isEmpty()) builder.append(", ids=").append(ids);
    return builder.replace(0, 2, "IntList{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<IntList, Builder> {
    public List<Integer> ids;

    public Builder() {
      ids = Internal.newMutableList();
    }

    public Builder ids(List<Integer> ids) {
      Internal.checkElementsNotNull(ids);
      this.ids = ids;
      return this;
    }

    @Override
    public IntList build() {
      return new IntList(ids, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_IntList extends ProtoAdapter<IntList> {
    ProtoAdapter_IntList() {
      super(FieldEncoding.LENGTH_DELIMITED, IntList.class);
    }

    @Override
    public int encodedSize(IntList value) {
      return ProtoAdapter.INT32.asRepeated().encodedSizeWithTag(1, value.ids)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, IntList value) throws IOException {
      ProtoAdapter.INT32.asRepeated().encodeWithTag(writer, 1, value.ids);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public IntList decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.ids.add(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public IntList redact(IntList value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
