// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: pwbox.proto at 123:1
package com.pw.box.bean.protobuf;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class ItemOfServer extends Message<ItemOfServer, ItemOfServer.Builder> {
  public static final ProtoAdapter<ItemOfServer> ADAPTER = new ProtoAdapter_ItemOfServer();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_ID = 0L;

  public static final ByteString DEFAULT_DATA = ByteString.EMPTY;

  public static final Integer DEFAULT_COMPRESSED = 0;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long id;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES"
  )
  public final ByteString data;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer compressed;

  public ItemOfServer(Long id, ByteString data, Integer compressed) {
    this(id, data, compressed, ByteString.EMPTY);
  }

  public ItemOfServer(Long id, ByteString data, Integer compressed, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.id = id;
    this.data = data;
    this.compressed = compressed;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.id = id;
    builder.data = data;
    builder.compressed = compressed;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ItemOfServer)) return false;
    ItemOfServer o = (ItemOfServer) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(id, o.id)
        && Internal.equals(data, o.data)
        && Internal.equals(compressed, o.compressed);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (id != null ? id.hashCode() : 0);
      result = result * 37 + (data != null ? data.hashCode() : 0);
      result = result * 37 + (compressed != null ? compressed.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (id != null) builder.append(", id=").append(id);
    if (data != null) builder.append(", data=").append(data);
    if (compressed != null) builder.append(", compressed=").append(compressed);
    return builder.replace(0, 2, "ItemOfServer{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<ItemOfServer, Builder> {
    public Long id;

    public ByteString data;

    public Integer compressed;

    public Builder() {
    }

    public Builder id(Long id) {
      this.id = id;
      return this;
    }

    public Builder data(ByteString data) {
      this.data = data;
      return this;
    }

    public Builder compressed(Integer compressed) {
      this.compressed = compressed;
      return this;
    }

    @Override
    public ItemOfServer build() {
      return new ItemOfServer(id, data, compressed, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_ItemOfServer extends ProtoAdapter<ItemOfServer> {
    ProtoAdapter_ItemOfServer() {
      super(FieldEncoding.LENGTH_DELIMITED, ItemOfServer.class);
    }

    @Override
    public int encodedSize(ItemOfServer value) {
      return (value.id != null ? ProtoAdapter.INT64.encodedSizeWithTag(1, value.id) : 0)
          + (value.data != null ? ProtoAdapter.BYTES.encodedSizeWithTag(2, value.data) : 0)
          + (value.compressed != null ? ProtoAdapter.INT32.encodedSizeWithTag(3, value.compressed) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, ItemOfServer value) throws IOException {
      if (value.id != null) ProtoAdapter.INT64.encodeWithTag(writer, 1, value.id);
      if (value.data != null) ProtoAdapter.BYTES.encodeWithTag(writer, 2, value.data);
      if (value.compressed != null) ProtoAdapter.INT32.encodeWithTag(writer, 3, value.compressed);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public ItemOfServer decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.id(ProtoAdapter.INT64.decode(reader)); break;
          case 2: builder.data(ProtoAdapter.BYTES.decode(reader)); break;
          case 3: builder.compressed(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public ItemOfServer redact(ItemOfServer value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
