// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: pwbox.proto at 60:1
package com.pw.box.bean.protobuf;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class LoginRes extends Message<LoginRes, LoginRes.Builder> {
  public static final ProtoAdapter<LoginRes> ADAPTER = new ProtoAdapter_LoginRes();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_RETCODE = 0;

  public static final String DEFAULT_DESCRIPTION = "";

  public static final String DEFAULT_TOKEN = "";

  public static final ByteString DEFAULT_RAW_KEY_BY_PW = ByteString.EMPTY;

  public static final Boolean DEFAULT_HAVE_PROTECTION = false;

  public static final Integer DEFAULT_DATA_VERSION = 0;

  public static final Long DEFAULT_MAX_DATA_ID = 0L;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer retCode;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String description;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String token;

  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES"
  )
  public final ByteString raw_key_by_pw;

  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean have_protection;

  @WireField(
      tag = 6,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer data_version;

  @WireField(
      tag = 7,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long max_data_id;

  public LoginRes(Integer retCode, String description, String token, ByteString raw_key_by_pw, Boolean have_protection, Integer data_version, Long max_data_id) {
    this(retCode, description, token, raw_key_by_pw, have_protection, data_version, max_data_id, ByteString.EMPTY);
  }

  public LoginRes(Integer retCode, String description, String token, ByteString raw_key_by_pw, Boolean have_protection, Integer data_version, Long max_data_id, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.retCode = retCode;
    this.description = description;
    this.token = token;
    this.raw_key_by_pw = raw_key_by_pw;
    this.have_protection = have_protection;
    this.data_version = data_version;
    this.max_data_id = max_data_id;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.retCode = retCode;
    builder.description = description;
    builder.token = token;
    builder.raw_key_by_pw = raw_key_by_pw;
    builder.have_protection = have_protection;
    builder.data_version = data_version;
    builder.max_data_id = max_data_id;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof LoginRes)) return false;
    LoginRes o = (LoginRes) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(retCode, o.retCode)
        && Internal.equals(description, o.description)
        && Internal.equals(token, o.token)
        && Internal.equals(raw_key_by_pw, o.raw_key_by_pw)
        && Internal.equals(have_protection, o.have_protection)
        && Internal.equals(data_version, o.data_version)
        && Internal.equals(max_data_id, o.max_data_id);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (retCode != null ? retCode.hashCode() : 0);
      result = result * 37 + (description != null ? description.hashCode() : 0);
      result = result * 37 + (token != null ? token.hashCode() : 0);
      result = result * 37 + (raw_key_by_pw != null ? raw_key_by_pw.hashCode() : 0);
      result = result * 37 + (have_protection != null ? have_protection.hashCode() : 0);
      result = result * 37 + (data_version != null ? data_version.hashCode() : 0);
      result = result * 37 + (max_data_id != null ? max_data_id.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (retCode != null) builder.append(", retCode=").append(retCode);
    if (description != null) builder.append(", description=").append(description);
    if (token != null) builder.append(", token=").append(token);
    if (raw_key_by_pw != null) builder.append(", raw_key_by_pw=").append(raw_key_by_pw);
    if (have_protection != null) builder.append(", have_protection=").append(have_protection);
    if (data_version != null) builder.append(", data_version=").append(data_version);
    if (max_data_id != null) builder.append(", max_data_id=").append(max_data_id);
    return builder.replace(0, 2, "LoginRes{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<LoginRes, Builder> {
    public Integer retCode;

    public String description;

    public String token;

    public ByteString raw_key_by_pw;

    public Boolean have_protection;

    public Integer data_version;

    public Long max_data_id;

    public Builder() {
    }

    public Builder retCode(Integer retCode) {
      this.retCode = retCode;
      return this;
    }

    public Builder description(String description) {
      this.description = description;
      return this;
    }

    public Builder token(String token) {
      this.token = token;
      return this;
    }

    public Builder raw_key_by_pw(ByteString raw_key_by_pw) {
      this.raw_key_by_pw = raw_key_by_pw;
      return this;
    }

    public Builder have_protection(Boolean have_protection) {
      this.have_protection = have_protection;
      return this;
    }

    public Builder data_version(Integer data_version) {
      this.data_version = data_version;
      return this;
    }

    public Builder max_data_id(Long max_data_id) {
      this.max_data_id = max_data_id;
      return this;
    }

    @Override
    public LoginRes build() {
      return new LoginRes(retCode, description, token, raw_key_by_pw, have_protection, data_version, max_data_id, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_LoginRes extends ProtoAdapter<LoginRes> {
    ProtoAdapter_LoginRes() {
      super(FieldEncoding.LENGTH_DELIMITED, LoginRes.class);
    }

    @Override
    public int encodedSize(LoginRes value) {
      return (value.retCode != null ? ProtoAdapter.INT32.encodedSizeWithTag(1, value.retCode) : 0)
          + (value.description != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.description) : 0)
          + (value.token != null ? ProtoAdapter.STRING.encodedSizeWithTag(3, value.token) : 0)
          + (value.raw_key_by_pw != null ? ProtoAdapter.BYTES.encodedSizeWithTag(4, value.raw_key_by_pw) : 0)
          + (value.have_protection != null ? ProtoAdapter.BOOL.encodedSizeWithTag(5, value.have_protection) : 0)
          + (value.data_version != null ? ProtoAdapter.INT32.encodedSizeWithTag(6, value.data_version) : 0)
          + (value.max_data_id != null ? ProtoAdapter.INT64.encodedSizeWithTag(7, value.max_data_id) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, LoginRes value) throws IOException {
      if (value.retCode != null) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.retCode);
      if (value.description != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.description);
      if (value.token != null) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.token);
      if (value.raw_key_by_pw != null) ProtoAdapter.BYTES.encodeWithTag(writer, 4, value.raw_key_by_pw);
      if (value.have_protection != null) ProtoAdapter.BOOL.encodeWithTag(writer, 5, value.have_protection);
      if (value.data_version != null) ProtoAdapter.INT32.encodeWithTag(writer, 6, value.data_version);
      if (value.max_data_id != null) ProtoAdapter.INT64.encodeWithTag(writer, 7, value.max_data_id);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public LoginRes decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.retCode(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.description(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.token(ProtoAdapter.STRING.decode(reader)); break;
          case 4: builder.raw_key_by_pw(ProtoAdapter.BYTES.decode(reader)); break;
          case 5: builder.have_protection(ProtoAdapter.BOOL.decode(reader)); break;
          case 6: builder.data_version(ProtoAdapter.INT32.decode(reader)); break;
          case 7: builder.max_data_id(ProtoAdapter.INT64.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public LoginRes redact(LoginRes value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
