// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: pwbox.proto at 79:1
package com.pw.box.bean.protobuf;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class SetProtect extends Message<SetProtect, SetProtect.Builder> {
  public static final ProtoAdapter<SetProtect> ADAPTER = new ProtoAdapter_SetProtect();

  private static final long serialVersionUID = 0L;

  public static final ByteString DEFAULT_OLD_ANSWER = ByteString.EMPTY;

  public static final String DEFAULT_NEW_QUESTION = "";

  public static final ByteString DEFAULT_NEW_ANSWER = ByteString.EMPTY;

  public static final ByteString DEFAULT_RAW_KEY_BY_ANSWER = ByteString.EMPTY;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES"
  )
  public final ByteString old_answer;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String new_question;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES"
  )
  public final ByteString new_answer;

  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES"
  )
  public final ByteString raw_key_by_answer;

  public SetProtect(ByteString old_answer, String new_question, ByteString new_answer, ByteString raw_key_by_answer) {
    this(old_answer, new_question, new_answer, raw_key_by_answer, ByteString.EMPTY);
  }

  public SetProtect(ByteString old_answer, String new_question, ByteString new_answer, ByteString raw_key_by_answer, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.old_answer = old_answer;
    this.new_question = new_question;
    this.new_answer = new_answer;
    this.raw_key_by_answer = raw_key_by_answer;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.old_answer = old_answer;
    builder.new_question = new_question;
    builder.new_answer = new_answer;
    builder.raw_key_by_answer = raw_key_by_answer;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof SetProtect)) return false;
    SetProtect o = (SetProtect) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(old_answer, o.old_answer)
        && Internal.equals(new_question, o.new_question)
        && Internal.equals(new_answer, o.new_answer)
        && Internal.equals(raw_key_by_answer, o.raw_key_by_answer);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (old_answer != null ? old_answer.hashCode() : 0);
      result = result * 37 + (new_question != null ? new_question.hashCode() : 0);
      result = result * 37 + (new_answer != null ? new_answer.hashCode() : 0);
      result = result * 37 + (raw_key_by_answer != null ? raw_key_by_answer.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (old_answer != null) builder.append(", old_answer=").append(old_answer);
    if (new_question != null) builder.append(", new_question=").append(new_question);
    if (new_answer != null) builder.append(", new_answer=").append(new_answer);
    if (raw_key_by_answer != null) builder.append(", raw_key_by_answer=").append(raw_key_by_answer);
    return builder.replace(0, 2, "SetProtect{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<SetProtect, Builder> {
    public ByteString old_answer;

    public String new_question;

    public ByteString new_answer;

    public ByteString raw_key_by_answer;

    public Builder() {
    }

    public Builder old_answer(ByteString old_answer) {
      this.old_answer = old_answer;
      return this;
    }

    public Builder new_question(String new_question) {
      this.new_question = new_question;
      return this;
    }

    public Builder new_answer(ByteString new_answer) {
      this.new_answer = new_answer;
      return this;
    }

    public Builder raw_key_by_answer(ByteString raw_key_by_answer) {
      this.raw_key_by_answer = raw_key_by_answer;
      return this;
    }

    @Override
    public SetProtect build() {
      return new SetProtect(old_answer, new_question, new_answer, raw_key_by_answer, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_SetProtect extends ProtoAdapter<SetProtect> {
    ProtoAdapter_SetProtect() {
      super(FieldEncoding.LENGTH_DELIMITED, SetProtect.class);
    }

    @Override
    public int encodedSize(SetProtect value) {
      return (value.old_answer != null ? ProtoAdapter.BYTES.encodedSizeWithTag(1, value.old_answer) : 0)
          + (value.new_question != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.new_question) : 0)
          + (value.new_answer != null ? ProtoAdapter.BYTES.encodedSizeWithTag(3, value.new_answer) : 0)
          + (value.raw_key_by_answer != null ? ProtoAdapter.BYTES.encodedSizeWithTag(4, value.raw_key_by_answer) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, SetProtect value) throws IOException {
      if (value.old_answer != null) ProtoAdapter.BYTES.encodeWithTag(writer, 1, value.old_answer);
      if (value.new_question != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.new_question);
      if (value.new_answer != null) ProtoAdapter.BYTES.encodeWithTag(writer, 3, value.new_answer);
      if (value.raw_key_by_answer != null) ProtoAdapter.BYTES.encodeWithTag(writer, 4, value.raw_key_by_answer);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public SetProtect decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.old_answer(ProtoAdapter.BYTES.decode(reader)); break;
          case 2: builder.new_question(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.new_answer(ProtoAdapter.BYTES.decode(reader)); break;
          case 4: builder.raw_key_by_answer(ProtoAdapter.BYTES.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public SetProtect redact(SetProtect value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
